---
# This role installs httpd

- name: Install http
  yum: name={{ item }} state=present
  with_items:
   - httpd
   - php
   - php-mysql
   - git
   
- name: Configure SELinux to allow httpd to connect to remote database
  seboolean: name=httpd_can_network_connect_db state=true persistent=yes
  when: sestatus.rc != 0

- name: http service state
  service: name=httpd state=started enabled=yes
 
##通过yum安装apache后，设置selinux使得apache可以允许链接到数据库
##然后重启服务设置开机启功
