---
# This playbook deploys two simple applications to JBoss server. 

- hosts: all

  roles:
# Optionally, (re)deploy JBoss here	  
#    - jboss-standalone
    - java-app



  ###在jboss server跑起来后执行-java-app角色，可以安装两个简单的应用程序
