---
# This role contains common plays that will run on all nodes.

- name: Install python bindings for SE Linux
  yum: name={{ item }} state=present
  with_items:
   - libselinux-python
   - libsemanage-python
##安装python环境
- name: Create the repository for EPEL
  copy: src=epel.repo dest=/etc/yum.repos.d/epel.repo
##给远程主机创建epel源
- name: Create the GPG key for EPEL
  copy: src=RPM-GPG-KEY-EPEL-6 dest=/etc/pki/rpm-gpg
##创建远程主机epel源的密钥
- name: install some useful nagios plugins
  yum: name={{ item }} state=present
  with_items:
   - nagios-nrpe
   - nagios-plugins-swap
   - nagios-plugins-users
   - nagios-plugins-procs
   - nagios-plugins-load
   - nagios-plugins-disk
##安装一些有用的nagios监控插件

- name: Install ntp
  yum: name=ntp state=present
  tags: ntp
##安装时间同步ntp
- name: Configure ntp file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  tags: ntp
  notify: restart ntp
##修改ntp配置文件，后重启

- name: Start the ntp service
  service: name=ntpd state=started enabled=yes
  tags: ntp
##启动ntp服务
# work around RHEL 7, for now
- name: insert iptables template
  template: src=iptables.j2 dest=/etc/sysconfig/iptables
  when: ansible_distribution_major_version != '7'
  notify: restart iptables
##当系统版本是7时，设置iptables规则，后重启防火墙
- name: test to see if selinux is running
  command: getenforce
  register: sestatus
  changed_when: false
##查看selinux状态，并保存到变量sestatus中
