---
# This playbook will install mysql and create db user and give permissions.

- name: Install Mysql package
  yum: name={{ item }} state=installed
  with_items:
   - mysql-server
   - MySQL-python
   - libselinux-python
   - libsemanage-python
#yum 安装mysqlserver
- name: Configure SELinux to start mysql on any port
  seboolean: name=mysql_connect_any state=true persistent=yes
  when: sestatus.rc != 0
##配置selinux可以放松mysql
- name: Create Mysql configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify:
  - restart mysql
##修改mysql配置文件后重启mysql

- name: Start Mysql Service
  service: name=mysqld state=started enabled=yes
## 启动mysql服务并设置开机自启动

- name: insert iptables rule
  lineinfile: dest=/etc/sysconfig/iptables state=present regexp="{{ mysql_port }}"
              insertafter="^:OUTPUT " line="-A INPUT -p tcp  --dport {{ mysql_port }} -j  ACCEPT"
  notify: restart iptables
##设置防火墙规则，重启防火墙

- name: Create Application Database
  mysql_db: name={{ dbname }} state=present
##取用变量创建mysql库

- name: Create Application DB User
  mysql_user: name={{ dbuser }} password={{ upassword }} priv=*.*:ALL host='%' state=present
##为所创建的库创建用户,密码，及访问权限控制
